version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=sigmalion
      - POSTGRES_PASSWORD=sigmalion
      - POSTGRES_DB=sigma_dpr
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
