import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'arg-azul': '#232D4F',
        'arg-secundario': '#3E5A7E',
        'arg-amarillo': '#E7BA61',
        'arg-verde': '#2E7D33',
        'arg-rojo': '#C62828',
        'arg-info': '#5A7290',
        'arg-arena': '#EAE1B7',
        'arg-negro': '#141414',
        'arg-gris-intermedio': '#555555',
        'arg-gris-niebla': '#F2F2F2',
        'arg-uva': '#6A1B99',
        'arg-arandano': '#C2185B',
        'arg-rosado': '#F48EAB',
        'arg-tomate': '#EF5350',
        'arg-marron-oscuro': '#511901',
        'arg-naranja': '#EF6C00',
        'arg-mandarina': '#F79D00',
        'arg-maiz': '#FFCE1C',
        'arg-verdin': '#6EA015',
        'arg-lima': '#B9CE39',
        'arg-verde-azulado': '#3B8681',
        'arg-palta': '#50B7B2',
        'arg-lavanda': '#9284BE',

        white: '#FFFFFF',
        black: '#000000',
        primary: '#0072BC',
        'primary-dark': '#005a9e',
        secondary: '#E8E6D9',
        'secondary-dark': '#d1cfc1',
        accent: '#0094d4',
        success: '#2e7d32',
        danger: '#d32f2f',
        warning: '#f57c00',
        info: '#0094d4',
        background: '#F2F2F2',
        'sidebar-bg': '#FFFFFF',
        'sidebar-text': '#555555',
        'sidebar-hover': '#e6e6e6',
        'topbar-bg': '#FFFFFF',
        'card-bg': '#FFFFFF',
        'text-primary': '#141414',
        'text-secondary': '#555555',
        'tag-green': '#2e7d32',
        'tag-red': '#d32f2f',
        'tag-yellow': '#f57c00',
        gray: {
          200: '#F2F2F2',
          300: '#e6e6e6',
        }
      },
      fontFamily: {
        sans: ['var(--font-roboto)', 'sans-serif'],
        roboto: ['var(--font-roboto)', 'sans-serif'],
        'encode-sans': ['var(--font-encode-sans)', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
}
export default config